import enum

class Regs(enum.Enum):

    DRUMFRQ = 0
    PRESSROLLFRQ = 1
    SLUDEGSUPPLYFRQ = 2
    SLUDEGSPREADFRQ = 3
    DCV = 4
    DCA = 5
    DRUMCOLLINGWATER = 6
    TRANSFORMERSTEMP = 7
    SLUDGEINPUT = 8
    SLUDGEOUTPUT = 9
    INPUTWATERRATE = 10
    OUTPUTWATERRATE = 11
    LEFTBALANCE = 12
    RIGHTBALANCE = 13
    KW = 36


class Coils(enum.Enum):

    READY = 48
    FIELDMODE = 49
    REMOTEMODE = 50
    MANUAL = 51
    AUTO = 52
    CAMMOTER = 53
    DRUMUNIT = 54
    PRESSROLL = 55
    TRANSFORMERS = 56
    DCSUPPLY = 57
    WASINGPUMP = 58
    SLUDGESUPPLY = 59
    SLUDGESPREAD = 60
    SLIPRINGCOLLINGFAN = 61
    AUTOMATICSTART = 62
    AUTOMATICSTOP = 63
    REMOTESTOP = 64
    OUTPUTCONVEYOR = 65
    # RESET                   = 94
    # WATCHDOG                = 95


class Alarms(enum.Enum):
    PANELEMERGENCYSTOP = 0
    OPEMERGENCYSTOP = 1
    LEFTEMERGENCYSTOP = 2
    RIGHTEMERGENCYSTOP = 3
    DRUMINVERTERFAULT = 4
    PRESSROLLINVERTERFAULT = 5
    SLUDGESPREADINVERTERFALUT = 6
    SLUDGESUPPLYINVERTERFAULT = 7
    CAMMOTEREOCRTRIP = 8
    DRUMEOCRTRIP = 9
    PRESSROLLEOCRTRIP = 10
    WASH1EOCRTRIP = 11
    WASH2EOCRTRIP = 12
    PANELCOOLINGPANEOCRTRIP = 13
    SLIPRINGCOOLINGPANFAULT = 14
    SLUDEGSUPPLYEOCRTRIP = 15
    SLUDEGSPREADEOCRTRIP = 16
    TRANSFORMERSEOCRTRIP = 19
    TRANSFORMERSTEMPOVER = 20
    SCRCURRENTOVER = 21
    SCRTEMPOVER = 22
    DCCURRENTOVER = 23
    TRANSFORMERSFRONTDOOROPEN = 24
    TRANSFORMERSBACKDOOROPEN = 25
    SCRPANELDOOROPEN = 26
    DEHYDRATORLEFTDOOROPEN = 27
    DEHYDRATORRIGHTDOOROPEN = 28
    BELTLEFTOUT = 29
    BELTRIGHTOUT = 30
    AIRPRESSUREDROP = 31
    COOLINGPANFAULT = 32
    DRUMCOOLINGWATERTEMPOVER = 33
    AIRPRESSURESOLVALVECPTRIP = 34
    SLIPRINGTEMPOVER = 35
    TRANSFORMERSACBTRIP = 36
    DRUMEXC = 37
    SCRAPEREXC = 38
    WASHINGEXC = 39
    # 근접센서
    PSENSOREXC = 40
    # 물탱크센서
    WTSENSOREXC = 41
    FILTEREXC = 42
    DONTUSE1 = 44
    DONTUSE2 = 45
    DONTUSE3 = 46
    DONTUSE4 = 47
    # FULLTIMEON                  = 48
    ENDLIST = 47


class AbnormalSignAlarm(enum.Enum):

    OUTOFTIME = 66
    LEFTBALANCE = 67
    RIGHTBALANCE = 68
    ENDLIST = 68


class Machine(enum.Enum):

    TERMOFREG = 100
    TERMOFCOIL = 160

    ALARMCOUNTSTART = 50
    EXCALARMSWITCHSTART = 128

    FIRSTCOIL = 0
    SECONDCOIL = 160
    THRIDCOIL = 320

    FIRSTREG = 0
    SECONDREG = 100
    THIRDREG = 200


class OperatingTime(enum.Enum):

    TOTALMIN = 14
    TOTALHOUR = 15
    DRUMMIN = 16
    DRUMHOUR = 17
    SLUDGESCRAPERMIN = 18
    SLUDGESCRAPERHOUR = 19
    CLEANERMIN = 20
    CLEANERHOUR = 21
    CLOSESENSORMIN = 22
    CLOSESENSORHOUR = 23
    WATERTANKMIN = 24
    WATERTANKHOUR = 25
    FILTERMIN = 26
    FILTERHOUR = 27


class Monitoring(enum.Enum):

    NUMBEROFBUTTONS = 4
    NUMBEROFLABELS = 16
    NUMBEROFDATA = 4


class OnOffCheck(enum.Enum):
    # 의정부 A,B,C
    UJB_A = 9600
    UJB_B = 9601
    UJB_C = 9602
    # 진건 A,B
    JG_A = 9603
    JG_B = 9604
    # 정관
    JK_A = 9605
    # 검단 A,B
    GD_A = 9606
    GD_B = 9607
    # 청난
    CN_A = 9608
